from tkinter import *
import numpy as np

root = Tk()
root.geometry("335x130")
root.title("Equation Solver")
root.minsize(335, 130)
root.maxsize(335, 130)
root.iconbitmap('./res/icon.ico')


def cal():
    x1 = 0 if e1.get().isspace() or len(e1.get()) == 0 else int(e1.get())
    x2 = 0 if e2.get().isspace() or len(e2.get()) == 0 else int(e2.get())
    x3 = 0 if e3.get().isspace() or len(e3.get()) == 0 else int(e3.get())
    y1 = 0 if e4.get().isspace() or len(e4.get()) == 0 else int(e4.get())
    y2 = 0 if e5.get().isspace() or len(e5.get()) == 0 else int(e5.get())
    y3 = 0 if e6.get().isspace() or len(e6.get()) == 0 else int(e6.get())
    z1 = 0 if e7.get().isspace() or len(e7.get()) == 0 else int(e7.get())
    z2 = 0 if e8.get().isspace() or len(e8.get()) == 0 else int(e8.get())
    z3 = 0 if e9.get().isspace() or len(e9.get()) == 0 else int(e9.get())
    c1 = 0 if e10.get().isspace() or len(e10.get()) == 0 else int(e10.get())
    c2 = 0 if e11.get().isspace() or len(e11.get()) == 0 else int(e11.get())
    c3 = 0 if e12.get().isspace() or len(e12.get()) == 0 else int(e12.get())

    A = np.array([[x1, y1, z1], [x2, y2, z2], [x3, y3, z3]])
    B = np.array([[c1], [c2], [c3]])
    invA = np.linalg.inv(A)
    C = invA @ B
    eResult.delete(0, END)
    eResult.insert(0, f'x = {C[0, 0]}, y = {C[1, 0]}, z = {C[2, 0]}')


lx1 = Label(root, text='  x1 =  ')
e1 = Entry(root, width=5, borderwidth=5)
lx2 = Label(root, text='  x2 =  ')
e2 = Entry(root, width=5, borderwidth=5)
lx3 = Label(root, text='  x3 =  ')
e3 = Entry(root, width=5, borderwidth=5)
ly1 = Label(root, text='  y1 =  ')
e4 = Entry(root, width=5, borderwidth=5)
ly2 = Label(root, text='  y2 =  ')
e5 = Entry(root, width=5, borderwidth=5)
ly3 = Label(root, text='  y3 =  ')
e6 = Entry(root, width=5, borderwidth=5)
lz1 = Label(root, text='  z1 =  ')
e7 = Entry(root, width=5, borderwidth=5)
lz2 = Label(root, text='  z2 =  ')
e8 = Entry(root, width=5, borderwidth=5)
lz3 = Label(root, text='  z3 =  ')
e9 = Entry(root, width=5, borderwidth=5)
lc1 = Label(root, text='  c1 =  ')
e10 = Entry(root, width=5, borderwidth=5)
lc2 = Label(root, text='  c2 =  ')
e11 = Entry(root, width=5, borderwidth=5)
lc3 = Label(root, text='  c3 =  ')
e12 = Entry(root, width=5, borderwidth=5)

bt = Button(root, text="Calculate", padx=12, bg="#F7DBD5", command=cal)
eResult = Entry(root, width=40, borderwidth=5)

lx1.grid(row=0, column=0)
e1.grid(row=0, column=1)
lx2.grid(row=1, column=0)
e2.grid(row=1, column=1)
lx3.grid(row=2, column=0)
e3.grid(row=2, column=1)
ly1.grid(row=0, column=2)
e4.grid(row=0, column=3)
ly2.grid(row=1, column=2)
e5.grid(row=1, column=3)
ly3.grid(row=2, column=2)
e6.grid(row=2, column=3)
lz1.grid(row=0, column=4)
e7.grid(row=0, column=5)
lz2.grid(row=1, column=4)
e8.grid(row=1, column=5)
lz3.grid(row=2, column=4)
e9.grid(row=2, column=5)
lc1.grid(row=0, column=6)
e10.grid(row=0, column=7)
lc2.grid(row=1, column=6)
e11.grid(row=1, column=7)
lc3.grid(row=2, column=6)
e12.grid(row=2, column=7)

bt.grid(row=4, column=0, columnspan=2)
eResult.grid(row=4, column=2, columnspan=6)

root.mainloop()
